 2018-01-17 15:29:45,358 [P12004/D2/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.7.4 application starting on ARES
 2018-01-17 15:29:45,408 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-01-17 15:29:45,423 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 15ms)
 2018-01-17 15:29:45,502 [P12004/D2/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-01-17 15:29:45,504 [P12004/D2/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-01-17 15:29:45,507 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:29:45,531 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 24ms)
 2018-01-17 15:29:45,531 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-01-17 15:29:45,533 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2018-01-17 15:29:45,563 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:29:45,563 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:29:45,564 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-01-17 15:29:45,564 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2018-01-17 15:29:45,564 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:29:45,565 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:29:45,565 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-01-17 15:29:45,567 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 1ms)
 2018-01-17 15:29:45,586 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:29:45,587 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:29:45,587 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-01-17 15:29:45,587 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2018-01-17 15:29:45,588 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:29:45,588 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:29:45,588 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-01-17 15:29:45,589 [P12004/D2/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2018-01-17 15:29:48,604 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:2889f3e5-2784-4b9b-ba66-a7a9214654ac
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:48,608 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:49,644 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:be817c2a-9de7-4b1a-9f5d-455a21306315
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:49,645 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:50,842 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:35a4e324-c83a-4b88-b023-620f773de229
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:50,842 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:52,036 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:cb9ddd02-4230-48b8-9eb6-f77c7d27131e
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:52,037 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:53,229 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:92733c83-437a-4857-940b-003c1667e0f4
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:53,230 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:54,509 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:ac14e856-6518-43ff-8c88-f6a0f7357d4d
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:54,509 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:55,709 [P12004/D2/T1] WARN  Umbraco.Core.Persistence.DbConnectionExtensions - Configured database is reporting as not being available! DataSource: cdb-event-web-dev.database.windows.net, InitialCatalog: claremont-explore-web-dev. Exception: System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.DbConnectionExtensions.IsAvailable(IDbConnection connection)
ClientConnectionId:f0e451a7-a2f9-42a5-8aae-e3c6198aefd7
Error Number:40615,State:1,Class:14
 2018-01-17 15:29:55,709 [P12004/D2/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = False
 2018-01-17 15:29:55,715 [P12004/D2/T1] ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
Umbraco.Core.Exceptions.UmbracoStartupFailedException: Umbraco cannot start. A connection string is configured but Umbraco cannot connect to the database.
   vid Umbraco.Core.CoreBootManager.EnsureDatabaseConnection()
   vid Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   vid Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete)
   vid Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
 2018-01-17 15:30:06,031 [P12004/D2/T12] ERROR UmbracoExamine.DataServices.UmbracoContentService - EXCEPTION OCCURRED reading GetAllUserPropertyNames
System.Data.SqlClient.SqlException (0x80131904): Cannot open server 'cdb-event-web-dev' requested by the login. Client with IP address '213.114.135.88' is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.
   vid System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   vid System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   vid System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   vid System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   vid System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   vid System.Data.SqlClient.SqlConnection.Open()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.<>c__DisplayClass20_0.<ExecuteAction>b__0()
   vid Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   vid Umbraco.Core.Persistence.Database.OpenSharedConnection()
   vid Umbraco.Core.Persistence.Database.BeginTransaction(IsolationLevel isolationLevel)
   vid Umbraco.Core.Scoping.Scope.get_Database()
   vid UmbracoExamine.DataServices.UmbracoContentService.GetAllUserPropertyNames()
ClientConnectionId:a26a8417-04f0-4cc7-ada4-935fcabcad5e
Error Number:40615,State:1,Class:14
 2018-01-17 15:30:06,073 [P12004/D2/T12] INFO  BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper - Building static application type cache.
 2018-01-17 15:30:06,107 [P12004/D2/T12] INFO  BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper - Building static application type cache.
 2018-01-17 15:30:06,273 [P12004/D2/T12] INFO  Umbraco.Core.MainDom - Stopping...
 2018-01-17 15:30:06,275 [P12004/D2/T12] INFO  Umbraco.Core.MainDom - Released MainDom.
 2018-01-17 15:30:36,375 [P12004/D2/T10] INFO  Umbraco.Core.UmbracoApplicationBase - Application shutdown. Details: InitializationError

_shutDownMessage=Initialization Error
HostingEnvironment initiated shutdown
HostingEnvironment orsakade avslut

_shutDownStack=   vid System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   vid System.Environment.get_StackTrace()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownInternal()
   vid System.Web.Hosting.HostingEnvironment.InitiateShutdownWithoutDemand()
   vid System.Web.HttpRuntime.ShutdownAppDomain(String stackTrace)
   vid System.Web.HttpRuntime.AppDomainShutdownTimerCallback(Object state)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.TimerQueueTimer.CallCallback()
   vid System.Threading.TimerQueueTimer.Fire()
   vid System.Threading.TimerQueue.FireNextTimers()
 2018-01-17 15:32:12,781 [P12004/D3/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco 7.7.4 application starting on ARES
 2018-01-17 15:32:12,808 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Determining hash of code files on disk
 2018-01-17 15:32:12,819 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Hash determined (took 11ms)
 2018-01-17 15:32:12,870 [P12004/D3/T1] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-01-17 15:32:12,872 [P12004/D3/T1] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-01-17 15:32:12,874 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:12,893 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 19ms)
 2018-01-17 15:32:12,893 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IApplicationStartupHandler
 2018-01-17 15:32:12,895 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IApplicationStartupHandler (took 1ms)
 2018-01-17 15:32:12,917 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:12,918 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:12,918 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter
 2018-01-17 15:32:12,918 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyEditorValueConverter (took 0ms)
 2018-01-17 15:32:12,919 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:12,919 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:12,919 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IPropertyValueConverter
 2018-01-17 15:32:12,921 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IPropertyValueConverter (took 2ms)
 2018-01-17 15:32:12,938 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:12,938 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:12,938 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.Mvc.SurfaceController
 2018-01-17 15:32:12,938 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.Mvc.SurfaceController (took 0ms)
 2018-01-17 15:32:12,939 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:12,939 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:12,939 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.WebApi.UmbracoApiController
 2018-01-17 15:32:12,940 [P12004/D3/T1] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.WebApi.UmbracoApiController (took 0ms)
 2018-01-17 15:32:15,053 [P12004/D3/T1] INFO  Umbraco.Core.DatabaseContext - CanConnect = True
 2018-01-17 15:32:16,117 [P12004/D3/T1] INFO  Umbraco.Web.Cache.CacheRefresherEventHandler - Initializing Umbraco internal event handlers for cache refreshing
 2018-01-17 15:32:16,159 [P12004/D3/T1] INFO  Umbraco.Web.Search.ExamineEvents - Initializing Examine and binding to business logic events
 2018-01-17 15:32:16,487 [P12004/D3/T1] INFO  BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper - Building static application type cache.
 2018-01-17 15:32:16,517 [P12004/D3/T1] INFO  BlueLeet.UCodeFirst.Helpers.UCodeFirstHelper - Building static application type cache.
 2018-01-17 15:32:16,628 [P12004/D3/T1] INFO  Umbraco.Web.Search.ExamineEvents - Adding examine event handlers for index providers: 5
 2018-01-17 15:32:16,686 [P12004/D3/T1] INFO  BlueLeet.UCodeFirst.ExamineEvents - Initializing BlueLeet index binding events
 2018-01-17 15:32:16,787 [P12004/D3/T1] INFO  BlueLeet.UCodeFirst.UCodeFirstApplicationEventHandler - uCodeFirst executed successfully in 82 ms.
 2018-01-17 15:32:16,965 [P12004/D3/T1] INFO  Umbraco.Core.Persistence.Database - New table 'claremontevent' was created
 2018-01-17 15:32:17,056 [P12004/D3/T1] INFO  Umbraco.Core.Persistence.Database - New table 'participants' was created
 2018-01-17 15:32:17,144 [P12004/D3/T1] INFO  Umbraco.Core.Persistence.Database - New table 'notifications' was created
 2018-01-17 15:32:17,232 [P12004/D3/T1] INFO  Umbraco.Core.Persistence.Database - New table 'jobinfo' was created
 2018-01-17 15:32:18,644 [P12004/D3/T1] INFO  Umbraco.Core.CoreBootManager - Umbraco application startup complete (took 5957ms)
 2018-01-17 15:32:18,894 [P12004/D3/T1] INFO  Hangfire.SqlServer.SqlServerStorage - Start installing Hangfire SQL objects...
 2018-01-17 15:32:19,025 [P12004/D3/T1] INFO  Hangfire.SqlServer.SqlServerStorage - Hangfire SQL objects installed.
 2018-01-17 15:32:19,062 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer - Starting Hangfire Server
 2018-01-17 15:32:19,068 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer - Using job storage: 'SQL Server: cdb-event-web-dev.database.windows.net@claremont-explore-web-dev'
 2018-01-17 15:32:19,068 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer - Using the following options for SQL Server job storage:
 2018-01-17 15:32:19,068 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer -     Queue poll interval: 00:00:15.
 2018-01-17 15:32:19,068 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer - Using the following options for Hangfire Server:
 2018-01-17 15:32:19,069 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer -     Worker count: 20
 2018-01-17 15:32:19,069 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer -     Listening queues: 'default'
 2018-01-17 15:32:19,069 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer -     Shutdown timeout: 00:00:15
 2018-01-17 15:32:19,069 [P12004/D3/T1] INFO  Hangfire.BackgroundJobServer -     Schedule polling interval: 00:00:15
 2018-01-17 15:32:19,170 [P12004/D3/T20] INFO  Umbraco.Core.Sync.ApplicationUrlHelper - ApplicationUrl: http://claremontexplore.se.local:80/umbraco (UmbracoModule request)
 2018-01-17 15:32:19,709 [P12004/D3/T20] INFO  umbraco.content - Load Xml from file...
 2018-01-17 15:32:19,778 [P12004/D3/T20] INFO  umbraco.content - Loaded Xml from file.
 2018-01-17 15:32:21,071 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:21,071 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:21,071 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Core.PropertyEditors.IParameterEditor
 2018-01-17 15:32:21,072 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Core.PropertyEditors.IParameterEditor (took 0ms)
 2018-01-17 15:32:41,347 [P12004/D3/T18] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:41,348 [P12004/D3/T18] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:41,348 [P12004/D3/T18] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2018-01-17 15:32:41,348 [P12004/D3/T18] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2018-01-17 15:32:41,558 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:41,558 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:41,558 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2018-01-17 15:32:41,559 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 0ms)
 2018-01-17 15:32:46,851 [P12004/D3/T14] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:32:46,853 [P12004/D3/T14] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: robert.ghafoor@claremont.se logged in from IP address 127.0.0.1
 2018-01-17 15:32:47,920 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:47,920 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:47,920 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.ITree
 2018-01-17 15:32:47,921 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.ITree (took 0ms)
 2018-01-17 15:32:47,948 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:47,948 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:47,949 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2018-01-17 15:32:47,949 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2018-01-17 15:32:47,955 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:47,955 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:47,955 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree
 2018-01-17 15:32:47,956 [P12004/D3/T10] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.TreeAttribute]umbraco.interfaces.ITree (took 0ms)
 2018-01-17 15:32:47,966 [P12004/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:47,966 [P12004/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:47,966 [P12004/D3/T14] INFO  Umbraco.Core.PluginManager - Resolving [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication
 2018-01-17 15:32:47,966 [P12004/D3/T14] INFO  Umbraco.Core.PluginManager - Resolved [umbraco.businesslogic.ApplicationAttribute]umbraco.interfaces.IApplication (took 0ms)
 2018-01-17 15:32:48,236 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:48,237 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:48,237 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper
 2018-01-17 15:32:48,237 [P12004/D3/T20] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Core.Persistence.Mappers.MapperForAttribute]Umbraco.Core.Persistence.Mappers.BaseMapper (took 0ms)
 2018-01-17 15:32:54,165 [P12004/D3/T13] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:32:57,460 [P12004/D3/T22] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-01-17 15:32:57,461 [P12004/D3/T22] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-01-17 15:32:57,461 [P12004/D3/T22] INFO  Umbraco.Core.PluginManager - Resolving umbraco.cms.businesslogic.macro.IMacroEngine
 2018-01-17 15:32:57,462 [P12004/D3/T22] INFO  Umbraco.Core.PluginManager - Resolved umbraco.cms.businesslogic.macro.IMacroEngine (took 0ms)
 2018-01-17 15:33:00,161 [P12004/D3/T20] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:33:20,139 [P12004/D3/T61] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2018-01-16 15:33:19
 2018-01-17 15:34:17,801 [P12004/D3/T61] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:34:46,859 [P12004/D3/T75] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:43:52,074 [P12004/D3/T91] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 15:45:27,884 [P12004/D3/T123] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username robert.ghafoor@claremont.se from IP address 127.0.0.1
 2018-01-17 16:45:02,676 [P12004/D3/T267] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: robert.ghafoor@claremont.se, IP Address: 127.0.0.1
